Repository MichelRahme/ConcordiaNavigation, pull requests merged in 2020-03, with the labels that each got.

#90 Temporary fix for Shuttle Widget
  lib/models/buildingModels/building_information.dart
  lib/models/buildingModels/building_list.dart
  lib/models/providers.dart
  lib/providers/shuttle_data.dart
  lib/widgets/building_widgets/building_marker.dart
  lib/widgets/map_widget.dart
Labels: hotfix

#89 Temporary fix for Shuttle Widget
  lib/models/buildingModels/building_information.dart
  lib/models/buildingModels/building_list.dart
  lib/models/providers.dart
  lib/providers/shuttle_data.dart
  lib/widgets/building_widgets/building_marker.dart
  lib/widgets/map_widget.dart
Labels: hotfix

#99 #84 Add map directions + fix #96 and #97 + #98 Change Directions List
  .travis.yml
  lib/models/itinerary.dart
  lib/providers/map_data.dart
  lib/services/location_search.dart
  lib/widgets/custom_drawer.dart
  lib/widgets/directions_appbar.dart
  lib/widgets/directions_drawer.dart
  lib/widgets/directions_widget.dart
  lib/widgets/homepage_appbar.dart
  lib/widgets/map_widget.dart
  pubspec.lock
Labels: enhancement, feature

#102 Add optional DateTime parameter to ShuttleData.getNextShuttle
  lib/providers/shuttle_data.dart
Labels: enhancement

#108 Separate DirectionsWidget from MapWidget
  ios/Podfile.lock
  lib/providers/map_data.dart
  lib/providers/shuttle_data.dart
  lib/screens/home_page.dart
  lib/services/location_search.dart
  lib/widgets/directions_appbar.dart
  lib/widgets/directions_drawer.dart
  lib/widgets/homepage_appbar.dart
  lib/widgets/map_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, refactor

#112 Add support for classrooms as destinations
  assets/destinations.json
  assets/shuttleSchedule.json
  lib/models/itinerary.dart
  lib/providers/shuttle_data.dart
  lib/services/location_search.dart
  lib/storage/app_constants.dart
  lib/widgets/directions_drawer.dart
  lib/widgets/shuttle_tile.dart
  pubspec.lock
  pubspec.yaml
  test/location_search_test.dart
Labels: feature, refactor

#117 Add new enhanced building markers and highlights
  assets/campus_buildings_info.txt
  assets/h.png
  assets/markers/cc.png
  assets/markers/cj.png
  assets/markers/ev.png
  assets/markers/fg.png
  assets/markers/ge.png
  assets/markers/h.png
  assets/markers/lb.png
  assets/markers/mb.png
  assets/markers/py.png
  assets/markers/sp.png
  lib/models/building.dart
  lib/models/buildingModels/building_information.dart
  lib/models/buildingModels/building_list.dart
  lib/storage/app_constants.dart
  lib/widgets/bottomsheet_widget.dart
  lib/widgets/building_widgets/building_marker.dart
  lib/widgets/map_widget.dart
  lib/widgets/shuttle_tile.dart
  pubspec.yaml
Labels: enhancement

#119 Refactor classes for testing
  lib/models/buildingModels/building_list.dart
  lib/models/itinerary.dart
  lib/services/directions_service.dart
  lib/services/location_service.dart
  lib/widgets/map_widget.dart
  test/location_search_test.dart
  test/models/buildingModels/building_information_test.dart
  test/models/buildingModels/building_list_test.dart
  test/models/building_test.dart
  test/models/user_location_test.dart
  test/providers/buildings_data_test.dart
  test/providers/map_data_test.dart
  test/services/location_search_test.dart
  test/widgets/custom_appbar_test.dart
  test/widgets/custom_drawer_test.dart
  test/widgets/floating_map_button_test.dart
  test/widgets/map_widget_test.dart
Labels: refactor, testing

#123 Refactored ShuttleData and updated unit tests
  lib/providers/shuttle_data.dart
  test/models/buildingModels/building_information_test.dart
  test/models/buildingModels/building_list_test.dart
  test/models/building_test.dart
  test/providers/shuttle_data_test.dart
  test/services/location_search_test.dart
  test/services/location_service_test.dart
Labels: refactor, testing

#154 Fix missing markers + refactor buildings
  lib/main.dart
  lib/models/building.dart
  lib/models/buildingModels/building_information.dart
  lib/models/outdoor_poi.dart
  lib/providers/buildings_data.dart
  lib/services/building_list.dart
  lib/services/building_outline.dart
  lib/widgets/bottomsheet_widget.dart
  lib/widgets/map_widget.dart
  lib/widgets/outdoor_interest_widget.dart
  test/models/buildingModels/building_information_test.dart
  test/models/buildingModels/building_list_test.dart
  test/models/buildingModels/building_test.dart
  test/models/building_test.dart
  test/widgets/custom_appbar_test.dart
  test/widgets/custom_drawer_test.dart
  test/widgets/map_widget_test.dart
Labels: bug, refactor
